name: scan
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  image:
    strategy:
      matrix:
        exclude:
        - from: focal
          release: zed
        - from: focal
          release: "2023.1"
        - from: jammy
          release: wallaby
        - from: jammy
          release: xena
        from:
        - focal
        - jammy
        release:
        - wallaby
        - xena
        - yoga
        - zed
        - "2023.1"
    runs-on: ubuntu-latest
    steps:
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: quay.io/vexxhost/horizon:${{ matrix.release }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          category: ${{ matrix.release }}
          sarif_file: 'trivy-results.sarif'
